# Generated by Django 5.0.6 on 2026-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
