# Generated by Django 5.0.6 on 2026-09-28 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField()),
                ('pickup_lon', models.FloatField()),
                ('pickup_label', models.CharField(blank=True, max_length=120)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lon', models.FloatField()),
                ('dropoff_label', models.CharField(blank=True, max_length=120)),
                ('weight_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('item_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('FOOD', 'Food'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('BOOKS', 'Books'), ('OTHER', 'Other')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('distance_km', models.FloatField(default=0.0)),
                ('predicted_fare', models.FloatField(default=0.0)),
                ('final_fare', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['sender'], name='orders_orde_sender__471803_idx'), models.Index(fields=['courier'], name='orders_orde_courier_5a2c8b_idx'), models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx')],
            },
        ),
    ]
