# Generated by Django 5.0.6 on 2026-10-07 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight_kg',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(20.0)]),
        ),
    ]
