module.exports = {
  content: [
    './templates/**/*.html',
    './templates/components/*.html',
    './templates/orders/*.html',
    './static/js/**/*.js',
    './*/**/*.html'
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          green:          '#22C55E',
          greenDark:      '#16A34A',
          greenLight:     '#4ADE80',
          greenDarkText:  '#15803D',
          greenTint:      '#F0FDF4',
          greenSoft:      '#DCFCE7',
          navy:           '#05192D',
          navyLight:      '#213147',
          navyMedium:     '#13253A',
          navySubtext:    '#5D6A77',
          navySubtextAlt: '#9BA3AB',
          grey:           '#E8E8EE',
          greyLight:      '#EFEFF5',
          greySubtle:     '#F7F7FC',
          greyMedium:     '#E1E1E8',
          greyDark:       '#848492',
          greyDarkText:   '#595D78',
          blue:           '#5EB1FF',
          blueDark:       '#257DFE',
          blueDarkText:   '#0065D1',
          red:            '#FF5400',
          redDark:        '#DD3400',
          redDarkText:    '#C01100',
          orange:         '#FF931E',
          orangeDark:     '#D87300',
          yellow:         '#FCCE0D',
          yellowDark:     '#CFA600',
          purple:         '#7933FF',
          pink:           '#FF6EA9',
          beige:          '#EFEBE4',
          beigeSubtle:    '#FFFBF3',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
      },
      minHeight: { 'touch': '44px' },
      minWidth:  { 'touch': '44px' },
    },
  },
  plugins: [],
};
